kytos-ng/telemetry_int

managers/int.py, tests/unit/test_int_manager.py
Closes #45 
This PR is on top of PR #35 
- Updated telemetry metadata payload based on augmented EP031 
- (changelog not updated since this NApps hasn't been released yet)
- Enabled and disabled an INT intra-EVC on a NoviFlow switch too:
```
2023-08-31 10:21:06,215 - INFO [uvicorn.access] (MainThread) 127.0.0.1:57940 - "POST /api/kytos/mef_eline/v2/evc/metadata HTTP/1.1" 201
2023-08-31 10:21:06,239 - INFO [uvicorn.access] (MainThread) 127.0.0.1:57918 - "POST /api/kytos/telemetry_int/v1/evc/enable HTTP/1.1" 201
2023-08-31 10:21:10,822 - INFO [uvicorn.access] (MainThread) 127.0.0.1:57918 - "GET /api/kytos/mef_eline/v2/evc/6c600b72e3c34b HTTP/1.1" 200
2023-08-31 10:21:37,185 - INFO [uvicorn.access] (MainThread) 127.0.0.1:37934 - "GET /api/kytos/mef_eline/v2/evc/6c600b72e3c34b HTTP/1.1" 200 …
```
=> refactor: updated telemetry metadata payload based on augmented EP031

managers/flow_builder.py, tests/conftest.py, tests/unit/test_flow_builder_inter_evc.py, tests/unit/test_flow_builder_intra_evc.py
Closes #52 
Closes #25 
This PR is on top of #51 
- Fixed inter EVC hop flows cookie value
- No need to update the changelog this NApp hasn't been released yet
- Covered with unit tests using this topology and collected the stored flows:
```
+----+                                              +----+
5|    |6                                            5|    |6
+---+----v---+            +------------+           +----+----v---+
1  |            |            |            |           |             |1
-------+            |3         2 |            |3        2 |             +-------
vlan  |     s1     +------------+    s2      +-----------+    s3       | vlan
101   |            |            |            |           |             | 102
|            |            |            |           | …
```
=> fix: hop flows are not setting telemetry_int cookie correctly, added unit test for inter evpl

main.py, openapi.yml
Closes #6 
- Added v1 openapi.yml spec for endpoints `POST /v1/evc/enable` and `POST /v1/evc/disable`
- Updated responses and status code on endpoints accordingly to spec
- This NApp doesn't have a changelog yet
- Rendered the API spec:
- Enabled and disabled and exercised the expected status codes
```
kytos $> 2023-10-03 12:31:02,006 - INFO [uvicorn.access] [httptools_impl.py:506:send] (MainThread) 127.0.0.1:33184 - "GET /api/kytos/mef_eline/v2/evc/9093192378aa4d HTTP/1.1" 200        
2023-10-03 12:31:02,007 - INFO [kytos.napps.kytos/telemetry_int] [int.py:79:enable_int] (MainThread) Enabling INT on EVC ids: ['9093192378aa4d'], force: False
2023-10-03 12:31:02,017 - INFO [uvicorn.access] [httptools_impl.py:506:send] (MainThread) 127.0.0.1:33198 - "GET …
```
=> feat: added v1 openapi.yml spec

kytos_api_helper.py, main.py, openapi.yml, tests/unit/test_main.py, utils.py
Closes #59 
This PR is on top of PR #56 
- Added `GET /v1/evc` on openapi.yml (the response content follows mef_eline content)
- Covered with unit test
- Changelog not needed to update this NApp hasn't been released yet
- Enabled INT on an EVC, listed it, then disabled it and made sure that `v1/evc` wouldn't list it:
```
❯ http http://localhost:8181/api/kytos/telemetry_int/v1/evc | jq               
{
"9093192378aa4d": {
"active": false,
"archived": false,
"backup_path": [],
"bandwidth": 0,
"circuit_scheduler": [],
"current_path": [
{
"id": "c8b55359990f89a5849813dc348d30e9e1f991bad1dcb7f82112bd35429d9b07",
"endpoint_a": {
"id": "00:00:00:00:00:00:00:01:4",
"name": "s1-eth4",
"port_number": 4,
"mac": "92:09:64:f9:31:36",
"switch": "00:00:00:00:00:00:00:01",
"type": "interface",
"nni": …
```
=> feat|refactor: added `GET /v1/evc` on openapi.yml 

exceptions.py, main.py, managers/int.py, tests/unit/test_int_manager.py
Closes #39 
- validate intra EVC UNIs must use different proxy ports
- this NApps hasn't been released yet, no need to update changelog
```
kytos $> 2023-10-10 13:04:03,459 - INFO [uvicorn.access] [httptools_impl.py:506:send] (MainThread) 127.0.0.1:34960 - "GET /api/kytos/mef_eline/v2/evc/b45f387345094d HTTP/1.1" 200       
2023-10-10 13:04:03,460 - INFO [uvicorn.access] [httptools_impl.py:506:send] (MainThread) 127.0.0.1:34954 - "POST /api/kytos/telemetry_int/v1/evc/enable HTTP/1.1" 409
```
- Tried to enable INT on an intra EVC using same proxy ports:
```
{
"description": "EVC b45f387345094d intra EVC UNIs must use different proxy ports",
"code": 409
}
```
- Solved the conflict and finally enabled:
```
2023-10-10 13:04:57,556 - INFO [uvicorn.access] [httptools_impl.py:506:send] …
```
=> feat: validate intra EVC UNIs must use different proxy ports

README.rst, main.py, managers/flow_builder.py, managers/int.py, settings.py, tests/unit/test_flow_builder_inter_evc.py, tests/unit/test_flow_builder_intra_evc.py, tests/unit/test_main.py, tests/unit/test_utils.py, utils.py
Closes #13 
Closes #43 
This PR is on top of PR #39 
This PR is also related to https://github.com/kytos-ng/of_multi_table/pull/21
- Integration with `of_multi_table` supporting `evpl` and `epl` table groups on table 2 and 3 by default. Subcribed to `kytos/of_multi_table.enable_table`
- Refactored flow_builder module aggregating it into a class and parametrizing the table groups accordingly based on existing `evpl` and `evpl` flows (this resulted in larger diffs, but it's mostly just code moving around)
- This NApp hasn't been released yet, so no need to update the changelog
- With `of_multi_table` also enabled and running with default settings, on NoviFlow lab I created an intra-evpl, intra-epl, inter-epl and inter-epl, I observed that all existing `"evpl"` table groups were installed on …
=> feat: integration with `of_multi_table` supporting `evpl` and `epl` table groups on table 2 and 3 by default

exceptions.py, main.py, managers/int.py, proxy_port.py, settings.py, tests/unit/test_flow_builder_inter_evc.py, tests/unit/test_flow_builder_intra_evc.py, tests/unit/test_int_manager.py, tests/unit/test_main.py, tests/unit/test_utils.py, utils.py
Closes #28 
- Initial PR supporting covergence for a (looped) link used as a proxy port
- started handling proxy port link_up|link_down events
- started handling mef_eline loaded event
- extracted a few methods to reuse flow installations/deletions
- initial dict structures to keep track of unis sources and proxy ports for subsequent PRs 
I tested out on INT lab the following cases with 2 inter EVPLs (sw1 and sw6) and one intra EVPL (on sw1):
- I also performed restarts to make sure it loaded correctly 
- I shut down a loop and observed that only the expected evcs got their flows removed falling back to mef_eline flows, I also had iperf3 running to make sure traffic would still flow with a temporary drop:
```
kytos $> 2023-11-13 12:41:10,036 - INFO [kytos.napps.kytos/of_core] …
```
=> feat: handle proxy port link, flows network convergence

main.py, tests/unit/test_main.py
Closes #66 
This PR is on top of PR #67
This PR depends on https://github.com/kytos-ng/mef_eline/pull/401
- feat: replaced `kytos/mef_eline.loaded` with `kytos/mef_eline.evcs_loaded`
- This NApp hasn't been released yet no need to update changelog
- Created with INT EVCs and restarted, the expected `srcs_pp` (source proxy ports) were correctly loaded too:
```
kytos $> controller.napps[('kytos', 'telemetry_int')].int_manager.srcs_pp                                                                                                                
...:                                                                                                                                                                                 
Out[1]: 
{'00:00:00:00:00:00:00:01:5': ProxyPort(Interface('s1-eth5', …
```
=> feat: replaced `kytos/mef_eline.loaded` with `kytos/mef_eline.evcs_loaded`

main.py, managers/int.py, tests/unit/test_int_manager.py, tests/unit/test_main.py
Closes #70 
This PR is on top of #68 
- Subscribed to `kytos/topology.interfaces.metadata.removed` to deactivate INT falling back to `mef_eline`
- Additions and update will be addressed on #61 
- I created two INT EVCs, and then deleted `proxy_port` metadata one UNI and observed flows getting removed, after that, I also force disabled the EVCs (used a force here since this is not the typical disabling workflow since the `proxy_port` metadata had been deleted):
```
❯ http http://localhost:8181/api/kytos/telemetry_int/v1/evc/ | jq '.[].metadata'
{
"telemetry": {
"enabled": true,
"status": "UP",
"status_reason": [],
"status_updated_at": "2023-11-17T01:16:21"
}
}
{
"telemetry": {
"enabled": true,
"status": "UP",
"status_reason": [],
"status_updated_at": "2023-11-17T01:17:45"
}
}
❯ http DELETE …
```
=> feat: subscribed to `kytos/topology.interfaces.metadata.removed` to deactivate INT falling back to `mef_eline`

main.py, managers/int.py, openapi.yml, tests/unit/test_int_manager.py, tests/unit/test_main.py, utils.py
Closes #30 
- added `PATCH /v1/evc/redeploy` INT EVCs and its openapi docs
- updated `POST /v1/evc/enable` to also remove flows upfront (same behavior as mef_eline)
- No need to update changelog since this NApp hasn't been released yet
I used `Novi01` and `Novi06` and tested the following cases with `iperf3` on the hosts:
- Redeployed a single EVC, observed INT flows getting removed and installed and their counters
- Enabled EVC with force true, observed NT flows getting removed and installed and their counters
- Redeployed all EVCs with empty body, observed all got redeployed
```
kytos $> 2023-11-28 18:16:15,132 - INFO [uvicorn.access] [httptools_impl.py:506:send] (MainThread) 127.0.0.1:46808 - "GET /api/kytos/mef_eline/v2/evc/?archived=false&metadata.telemetry. …
```
=> feat: added PATCH /v1/evc/redeploy INT EVCs 

kytos_api_helper.py, tests/unit/test_kytos_api_helper.py
closes #73 
This depends on [this flow_manager PR](https://github.com/kytos-ng/flow_manager/pull/177)
This PR is on top of PR #72 
- filter `cookie_range` on /stored_flows endpoint via json body instead
- this NApp hasn't been released yet no need to update changelog
- Enabled and disabled INT, confirmed the flows got filtered as expected
- Ran sdntrace cp
N/A yet
=> chore: filter `cookie_range` on /stored_flows endpoint via json body instead

managers/int.py, tests/unit/test_int_manager.py
It depends on https://github.com/kytos-ng/of_lldp/pull/101 landing first
- Removed temporary asyncio.sleep related to https://github.com/kytos-ng/of_lldp/issues/100
- This NApp hasn't been relased yet, so no need to update changelog
- Simulated proxy port going down
- Simulated both proxy ports going up
```
kytos $> 2023-12-12 16:12:21,787 - INFO [kytos.napps.kytos/of_core] [main.py:701:update_port_status] (MainThread) PortStatus modified interface 00:00:00:00:00:00:00:03:5 state OFPPS_LIV
E
2023-12-12 16:12:21,788 - INFO [kytos.napps.kytos/of_core] [main.py:701:update_port_status] (MainThread) PortStatus modified interface 00:00:00:00:00:00:00:03:6 state OFPPS_LIVE
2023-12-12 16:12:21,790 - INFO [kytos.napps.kytos/mef_eline] [main.py:782:handle_interface_link_up] (dynamic_single_0) Event …
```
=> chore: removed tmp link up sleep

kytos_api_helper.py, main.py, managers/int.py, openapi.yml, tests/unit/test_main.py
Closes #29 
- Added GET v1/evc/compare endpoint
- This NApp hasn't been released yet so no need to update changelog
I explored the following cases on INT lab:
- Initially, no comparison inconsistencies with one INT evc:
```
❯ http http://localhost:8181/api/kytos/telemetry_int/v1/evc/compare
HTTP/1.1 200 OK
content-length: 2
content-type: application/json
date: Wed, 03 Jan 2024 20:21:06 GMT
server: uvicorn
[]
```
- I deleted with flow manager intentionally INT flows, but kept the metadata:
```
❯ http http://localhost:8181/api/kytos/telemetry_int/v1/evc/compare                                                                                           
HTTP/1.1 200 OK
content-length: 89
content-type: application/json
date: Wed, 03 Jan 2024 20:20:19 GMT
server: uvicorn
[
{
"compare_reason": [ …
```
=> feat: added `GET v1/evc/compare` endpoint

main.py, managers/int.py, tests/unit/test_int_manager.py
Closes #61
- feat: handled event ``kytos/topology.interfaces.metadata.added`` by updating (disabling and enabling) INT EVCs accordingly
- No need to update this NApp changelog yet since it's hasn't been released yet
- Using AmLight INT lab with `Novi01` and `Novi06` I updated `"00:00:00:00:00:00:00:01:15"` metadata from `{"proxy_port": 17}` to `{"proxy_port: 19"}` with one INT EVC in place, it was observed that it disabled and enabled it again as expected and `sdntrace_cp` correctly traced after it:
```
kytos $> 2024-01-08 15:18:14,425 - INFO [uvicorn.access] [httptools_impl.py:506:send] (MainThread) 127.0.0.1:35286 - "POST /api/kytos/topology/v3/interfaces/00%3A00%3A00%3A00%3A00%3A00%3
A00%3A01%3A15/metadata HTTP/1.1" 201
2024-01-08 15:18:14,433 - INFO [uvicorn.access] …
```
=> feat: handled kytos/topology.interfaces.metadata.added

kytos_api_helper.py, setup.cfg, tests/conftest.py, tests/unit/test_int_manager.py, tests/unit/test_kytos_api_helper.py, tests/unit/test_main.py, tests/unit/test_utils.py, tox.ini
Closes #77 
- Supported py 3.11 on unit tests
- Increased overall test cov to 90%
- No need to update changelog for this
```
---------- coverage: platform linux, python 3.11.8-final-0 -----------
Name                                        Stmts   Miss  Cover
---------------------------------------------------------------
__init__.py                                     0      0   100%
exceptions.py                                  31      4    87%
kytos_api_helper.py                            76     15    80%
main.py                                       212     87    59%
managers/__init__.py                            0      0   100%
managers/flow_builder.py                      128      3    98%
managers/int.py                               279     52    81%
proxy_port.py …
```
=> chore: supported py 3.11 unit tests, increased overall test cov to 90%

CHANGELOG.rst, main.py, tests/unit/test_main.py
Closes #84 
- Disabled an EVC which had telemetry enabled on NoviFlow lab, observed that it removed and updated metadata:
```
kytos $> 2024-04-16 12:53:11,077 - INFO [kytos.napps.kytos/flow_manager] (AnyIO worker thread) Send FlowMod from request dpid: 00:00:00:00:00:00:00:06, command: delete, force: True,  fl
ows[0, 1]: [{'cookie': 12288710410465943630, 'cookie_mask': 18446744073709551615}]
2024-04-16 12:53:11,083 - INFO [uvicorn.access] (MainThread) 127.0.0.1:60582 - "POST /api/kytos/flow_manager/v2/delete/00%3A00%3A00%3A00%3A00%3A00%3A00%3A06 HTTP/1.1" 202
2024-04-16 12:53:11,085 - INFO [kytos.napps.kytos/flow_manager] (AnyIO worker thread) Send FlowMod from request dpid: 00:00:00:00:00:00:00:01, command: delete, force: True,  flows[0, 1]
: [{'cookie': …
```
=> feat: handled kytos/mef_eline.undeployed event

CHANGELOG.rst, main.py, tests/unit/test_main.py
Closes #42 
This PR is on top of PR #85 
See updated changelog file. For more information about the [events check out EP031](https://github.com/kytos-ng/kytos/pull/468)
I tested all the three subscribed events on NoviFlow lab at AmLight too:
- Handling  `mef_eline.error_redeployed_link_down`:
```
kytos $> 2024-04-17 09:40:07,043 - INFO [kytos.napps.kytos/of_core] (MainThread) PortStatus modified interface 00:00:00:00:00:00:00:06:11 state OFPPS_LINK_DOWN
2024-04-17 09:40:07,047 - INFO [kytos.napps.kytos/mef_eline] (dynamic_single_0) Event handle_link_down Link(Interface('novi_port_11', 11, Switch('00:00:00:00:00:00:00:01')), Interface('
novi_port_11', 11, Switch('00:00:00:00:00:00:00:06')), d7e3aade462df35a656320b717e8603a7fd624c4cfb7dcb72feafe95c6be1c96)
2024-04-17 09:40:07,047 - INFO …
```
=> feat: handled kytos/mef_eline.(redeployed_link_down|redeployed_link_up)

CHANGELOG.rst, managers/flow_builder.py, managers/int.py, tests/unit/test_flow_builder_intra_evc.py, tests/unit/test_int_manager.py
Closes #87 
This is on top of PR #86 
See updated changelog file
I tested on AmLight INT Lab the following cases 
- Enabled INT on an inactive EVC, observed metadata was updated accordingly
- Enabled INT on an active EVC, observed metadata was updated accordingly
```
❯ http http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc/9461d30603ae44 | jq
{
"active": false,
"archived": false,
"backup_path": [],
"bandwidth": 0,
"circuit_scheduler": [],
"current_path": [],
"dynamic_backup_path": true,
"enabled": true,
"failover_path": [],
"id": "9461d30603ae44",
"metadata": {
"telemetry": {
"enabled": true,
"status": "DOWN",
"status_reason": [
"no_flows"
],
"status_updated_at": "2024-04-22T14:54:19"
}
},
"name": "inter_evpl_2222",
"primary_path": [],
"service_level": 6,
"uni_a": {
"tag": {
"tag_type": …
```
=> fix: only raise FlowsNotFound when it's active and flows aren't found

CHANGELOG.rst, README.rst, main.py, tests/unit/test_main.py
Closes #89 
This is on top of PR #88
- Tested on AmLight INT lab with two EVCs and flapping the UNI state:
```
kytos $> 2024-04-24 15:17:21,170 - INFO [kytos.napps.kytos/of_core] (MainThread) PortStatus modified interface 00:00:00:00:00:00:00:01:15 state OFPPS_LINK_DOWN
2024-04-24 15:17:21,272 - INFO [kytos.napps.kytos/mef_eline] (thread_pool_sb_56) Event handle_interface_link_down Interface('novi_port_15', 15, Switch('00:00:00:00:00:00:00:01'))
2024-04-24 15:17:21,273 - INFO [kytos.napps.kytos/mef_eline] (thread_pool_sb_56) Deactivating EVC 5608a913b43c4b. Interfaces: {'00:00:00:00:00:00:00:01:15': {'status': 'DOWN', 'status_r
eason': {'deactivated'}}}.
2024-04-24 15:17:21,278 - INFO [kytos.napps.kytos/telemetry_int] (MainThread) Handling …
```
=> feat: handled kytos/mef_eline.uni_active_updated

CHANGELOG.rst, main.py, managers/int.py, tests/unit/test_main.py
Closes #94 
This is on top of PR #95 
- Tried to redeploy an EVC without INT, resulted in 409, and then enabled and redeployed:
```
{
"description": "EVC ad4e4c63cf154b INT isn't enabled",
"code": 409
}
```
```
2024-05-01 16:54:00,173 - INFO [uvicorn.access] (MainThread) 127.0.0.1:57882 - "PATCH /api/kytos/telemetry_int/v1/evc/redeploy HTTP/1.1" 409
2024-05-01 16:54:21,556 - INFO [uvicorn.access] (MainThread) 127.0.0.1:58798 - "GET /api/kytos/mef_eline/v2/evc/ad4e4c63cf154b HTTP/1.1" 200
2024-05-01 16:54:21,563 - INFO [uvicorn.access] (MainThread) 127.0.0.1:58802 - "GET /api/kytos/flow_manager/v2/stored_flows?state=installed&state=pending HTTP/1.1" 200
2024-05-01 16:54:21,564 - INFO [kytos.napps.kytos/telemetry_int] (MainThread) Enabling INT on EVC ids: …
```
=> fix: validate has int when redeploying

main.py, tests/unit/test_main.py
Closes #98 
chore: refactored to use content id instead of content evc_id; internal refactoring no need to update changelog here on this NApp side.
Exercised some of the events with telemetry_int:
```
kytos $> 2024-05-16 13:49:27,329 - INFO [kytos.napps.kytos/mef_eline] (AnyIO worker thread) Removing EVC(df66e1705b1849, epl)
2024-05-16 13:49:27,332 - INFO [kytos.napps.kytos/flow_manager] (AnyIO worker thread) Send FlowMod from request dpid: 00:00:00:00:00:00:00:03, command: delete, force: True,  flows[0, 1
]: [{'cookie': 12312673024692918345, 'cookie_mask': 18446744073709551615}]
2024-05-16 13:49:27,338 - INFO [uvicorn.access] (MainThread) 127.0.0.1:41726 - "POST /api/kytos/flow_manager/v2/delete/00%3A00%3A00%3A00%3A00%3A00%3A00%3A03 HTTP/1.1" 202
2024-05-16 13:49:27,344 - INFO …
```
=> chore: refactored to use content id instead of content evc_id

CHANGELOG.rst, main.py, managers/flow_builder.py, managers/int.py, tests/unit/test_flow_builder_failover.py, tests/unit/test_flow_builder_intra_evc.py, tests/unit/test_int_manager.py, tests/unit/test_main.py, tests/unit/test_utils.py, utils.py
Closes #90 
Closes #33 
Closes #38 
Closes #105 
Functionality-wise it's been implemented, it'll keep it in draft while I'm finish the unit tests, and also I need to re-stress test when the INT lab is available again this week. 
- I explored all failover related events with dynamic EVCs, and measured a convergence with a link of the current_path going down on one EVC with `iperf3`, it has been on par with prior metrics compared to how `mef_eline` performs (a few thousands packets retransmissions at 9.5 Gbits/sec):
```
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-60.00  sec  66.0 GBytes  9.44 Gbits/sec  1085             sender
[  4]   0.00-60.00  sec  65.9 GBytes  9.44 Gbits/sec                  receiver
```
```
[ ID] Interval …
```
=> feat: subscribe and handle `kytos/mef_eline.(failover_link_down|failover_old_path|failover_deployed)`

CHANGELOG.rst, ui/k-info-panel/show_telemetry_int_data.kytos, ui/k-toolbar/main.kytos
Closes #92
Closes #93 
The UI for the telemetry_int napp was added. It allows the user to view a list of available EVCs and their corresponding INT data. You can also enable, disable, and redeploy INT on a set of chosen EVCs via the UI. 
You can filter the EVCs based on specific characteristics with the corresponding search columns. Data is saved within local storage to maintain the state of the search columns between each session.
An image below of the telemetry_int UI can be seen:
A combination of all parameters were used all at once to ensure functionality.
INT was enabled, disabled, and redeployed on a single EVC.
To test the new local storage functionality the page was refreshed and the data stayed the same.
=> Added UI to telemetry_int

CHANGELOG.rst, exceptions.py, main.py, managers/int.py, settings.py, tests/unit/test_int_manager.py
Closes #110 
Configuration for metadata will be covered on issue #112 
I've explored four test cases:
1) Tried to enable in the same request with a shared proxy port, returned validation error
2) Tried to enable in different requests with a shared proxy port, returned validation error
3) I updated `proxy_port` metadata via `topology` and it fixed it automatically by enabling it again now that the meadata wasn't conflicting
3) I updated `proxy_port` metadata to be conflicting again, and it logged the error and also updated metadata with status `["proxy_port_shared"]`.
```
2024-07-26 12:30:01,883 - INFO [uvicorn.access] (MainThread) 127.0.0.1:47712 - "POST /api/kytos/mef_eline/v2/evc/metadata HTTP/1.1" 201
2024-07-26 12:30:01,885 - ERROR …
```
=> feat: validate shared proxy port

CHANGELOG.rst, managers/int.py
Closes #116 
This PR is on top of PR #117 
- Tested out with 101 EVCs, and confirmed with sdntrace_cp too over all EVCs it traced correctly after simulating many network failures:
```
With 101 INT EVCs failover convergence:
iperf3 -c 10.22.22.3 -i 1 -t 60 -b 10G
Connecting to host 10.22.22.3, port 5201
[  4] local 10.22.22.2 port 59092 connected to 10.22.22.3 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  1.02 GBytes  8.72 Gbits/sec  319   1.86 MBytes       
[  4]   1.00-2.00   sec  1.11 GBytes  9.56 Gbits/sec    0   1.86 MBytes       
[  4]   2.00-3.00   sec  1.11 GBytes  9.56 Gbits/sec    0   1.86 MBytes       
[  4]   3.00-4.00   sec  1.11 GBytes  9.56 Gbits/sec    0   1.86 MBytes       
[  4]   4.00-5.00 …
```
=> fix: fixed batch flows slicing

managers/int.py, tests/unit/test_flow_builder_failover.py, tests/unit/test_utils.py, utils.py
Closes #119 
- Optimized away redudant `push_int` flows when handling failover events.. No need for changelog to be updated since it's an optimization on code that hasn't been released yet. 
- Confirmed that only a single INT flow was generated per mef_eline ingress flow:
```
2024-07-30 10:01:03,889 - INFO [kytos.napps.kytos/flow_manager] (thread_pool_app_5) Send FlowMod from KytosEvent dpid: 00:00:00:00:00:00:00:01, command: add, force: False, n_flows 1  flows[0, 1]: [{'match': {'in_port': 15, 'dl_vlan': 2222}, 'cookie': 12293275523393756481, 'actions': [{'action_type': 'push_vlan', 'tag_type': 's'}, {'action_type': 'set_vlan', 'vlan_id': 1
}, {'action_type': 'output', 'port': 2}], 'owner': 'mef_eline', 'table_group': 'evpl', 'table_id': 0, 'priority': 20000}]
2024-07-30 10:01:03,896 - …
```
=> fix: optimized away redudant push_int flows when handling failover events

CHANGELOG.rst, managers/int.py, settings.py
Closes #47
Removes client side batching.
Not something I can truly test beyond making sure that flow mods are sent when expected, which they still seem to be.
=> Remove Client Side Batching

CHANGELOG.rst, kytos_api_helper.py, main.py, managers/int.py, openapi.yml, settings.py, setup.py, tests/unit/test_int_manager.py, tests/unit/test_kytos_api_helper.py, tests/unit/test_main.py
Closes #112 
- Exercises many cases, including updating a proxy port and UNI values and all the crud operations on the new endpoints, they all behaved as expected:
```
❯ http http://localhost:8181/api/kytos/telemetry_int/v1/uni/proxy_port
HTTP/1.1 200 OK
content-length: 421
content-type: application/json
date: Thu, 08 Aug 2024 14:59:25 GMT
server: uvicorn
[
{
"proxy_port": {
"port_number": 5,
"status": "UP",
"status_reason": []
},
"uni": {
"id": "00:00:00:00:00:00:00:01:1",
"status": "UP",
"status_reason": []
}
},
{
"proxy_port": {
"port_number": 7,
"status": "UP",
"status_reason": []
},
"uni": {
"id": "00:00:00:00:00:00:00:01:2",
"status": "UP",
"status_reason": []
}
},
{
"proxy_port": {
"port_number": 5,
"status": "UP",
"status_reason": []
},
"uni": {
"id": …
```
=> feat: introduced create, delete and list proxy_port endpoints with validations

CHANGELOG.rst, kytos.json, main.py
Closes #129 
- See updated changelog file 
- As mentioned on issue 129, this wasn't absolutely necessary here yet, since mef_eline is already copying, but to avoid future accidental and making the intention clear, it's appropriate to already ship this, and it's expected that the number of flows here wouldn't bee to high (hundreds of thousands) in these events, so the deepcopy at the moment, isn't expected to be too expensive to compute
- Created an INT evpl, simulated failover events, and traced:
```
kytos $> 2024-08-30 10:27:30,881 - INFO [kytos.napps.kytos/of_core] (MainThread) PortStatus modified interface 00:00:00:00:00:00:00:01:11 state OFPPS_LINK_DOWN
2024-08-30 10:27:30,885 - INFO [kytos.napps.kytos/mef_eline] (dynamic_single_0) Event handle_link_down Link(Interface('novi_port_11', …
```
=> hotfix 2024.1.2: Prevented shared flow accidental mutability when handling failover flows

CHANGELOG.rst, ui/k-info-panel/list_proxy_ports.kytos, ui/k-info-panel/show_telemetry_int_data.kytos
Closes #N/A
A new modal component was added to the UI repository. This pull request makes it so that the telemetry_int UI now utilizes the new modal component.
The new modal component was used on a single EVC with telemetry enabled and it functioned as should.
Successfully deleted 3 proxy ports.
Description - UI repo in which the new modal component was implemented
- https://github.com/kytos-ng/ui/pull/80
=> Telemetry_INT Modal Utilizes New Modal Component

CHANGELOG.rst, ui/k-info-panel/show_telemetry_int_data.kytos
Closes #139 
There was a missing closing tag within the `show_telemetry_int_data` info panel.
=> Added missing tag

CHANGELOG.rst, ui/k-info-panel/list_proxy_ports.kytos
Closes #142 
K-inputs now use the new `customClass` prop to add their CSS classes instead of just using `class`, so that they are compatible with the vue3-sfc-loader.
For these changes to work, you need the latest custom class additions from the main UI repo:
https://github.com/kytos-ng/ui/pull/118#issue-2727981658
I ran it on my local environment and no errors were produced.
=> Added customClass to k-inputs

CHANGELOG.rst, tests/unit/test_utils.py, utils.py
Closes #154 
- Same as https://github.com/kytos-ng/telemetry_int/pull/156 
- See updated changelog file 
- Same as the linked backport PR
- N/A yet
=> fixed `get_id_from_cookie(cookie)` evc_id conversion leading zeros issue
